Repository Eureka-final-popco/Popco-Front, pull requests merged in 2025-08, with the labels that each got.

#73 [POP-276} Feat: 리뷰 상세페이지 연동
  src/apis/collectionApi.ts
  src/apis/reviewApi.ts
  src/components/MainPage/HeroReview.tsx
  src/components/MainPage/HeroReview2.tsx
  src/components/MainPage/HeroReview3.tsx
  src/components/MyPage/PageContents.tsx
  src/components/ReviewModal/ReviewModal.tsx
  src/components/collection/AddToCollectionModal.tsx
  src/components/common/ReviewCard.tsx
  src/components/detail/ActionButtons.tsx
  src/components/detail/ReviewSection.tsx
  src/hooks/useReviews.ts
  src/pages/DetailPage.tsx
  src/types/Reviews.types.ts
Labels: BUG, FEAT

#85 [POP-283] Fix: 좋아요 싫어요 연동 및 콘솔 제거
  src/apis/contentsApi.ts
  src/apis/recommendApi.ts
  src/apis/reviewApi.ts
  src/apis/tokenApi.ts
  src/apis/userApi.ts
  src/components/MainPage/HeroRanking.tsx
  src/components/MainPage/HeroTop1.tsx
  src/components/ReviewModal/ReviewModal.tsx
  src/components/common/Header.tsx
  src/components/common/Poster.tsx
  src/components/common/SearchBar.tsx
  src/components/popcorn/PopcornButtonBase.tsx
  src/hooks/queries/contents/useAllContents.ts
  src/hooks/queries/contents/useContentReaction.ts
  src/hooks/useContentsDetail.ts
  src/hooks/useReviews.ts
  src/index.css
  src/pages/CollectionDetailPage.tsx
  src/pages/DetailPage.tsx
  src/pages/ListPage.tsx
  src/pages/MyPage.tsx
  src/types/Contents.types.ts
  src/types/Popcorn.types.ts
Labels: BUG, FEAT

#86 [POP-284] Design: 마이페이지 하단 마진 추가
  src/components/MyPage/PageContents.tsx
Labels: STYLE

#87 [POP-285] Design: 담당페이지 디자인2차수정
  src/components/Analysis/LikeContentsSection.tsx
  src/components/Analysis/MyStyleSection.tsx
  src/components/MyPage/PageContents.tsx
  src/components/common/Header.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: STYLE, FEAT

#88 Fix: 최종 수정
  src/apis/tokenApi.ts
  src/apis/userApi.ts
  src/components/detail/ReviewSection.tsx
  src/constants/persona.ts
  src/hooks/useAuthCheck.ts
  src/pages/CollectionPage.tsx
  src/store/useLikeStore.ts
Labels: BUG

#89 [POP-211] Feat : 퀴즈 레이아웃, 퀴즈 socket 연동, 실시간 알림 SSE 연동
  Dockerfile
  index.html
  package-lock.json
  package.json
  public/images/popco/correct.svg
  public/images/popco/incorrect.svg
  public/images/popco/quiz.svg
  public/images/popco/time-popco.png
  public/images/popco/winner.svg
  src/apis/quizApi.ts
  src/components/EventPage/Countdown.tsx
  src/components/EventPage/PosterBackground.tsx
  src/components/EventPage/PosterImage.tsx
  src/components/EventPage/TimeBlock.tsx
  src/components/EventPage/cards/Eliminated.tsx
  src/components/EventPage/cards/EventInfoCard.tsx
  src/components/EventPage/cards/FinalWinner.tsx
  src/components/EventPage/cards/Question.tsx
  src/components/EventPage/cards/WaitingRoom.tsx
  src/hooks/queries/quiz/useQuizInfo.ts
  src/hooks/useMediaQuery.ts
  src/pages/EventPage.tsx
  src/routes/Layout.tsx
  src/routes/index.tsx
  src/stores/useQuizStore.ts
  src/types/Quiz.types.ts
  src/types/custom.d.ts
  src/utils/mapper.ts
  src/utils/socket.ts
  vite.config.ts
Labels: BUILD, CHORE, FEAT
