Repository Eureka-final-popco/Popco-Front, pull requests merged in 2025-07, with the labels that each got.

#17 [POP-162] Feat: 싫어요 버튼
  public/images/components/hate-popcorn.svg
  src/components/common/HatePopcorn.tsx
  src/components/common/LikePopcorn.tsx
Labels: STYLE, FEAT

#20 [POP-155] Feat: 포스터 컴포넌트
  package-lock.json
  package.json
  src/components/common/HatePopcorn.tsx
  src/components/common/LikePopcorn.tsx
  src/components/common/Poster.tsx
  src/components/popcorn/HatePopcorn.tsx
  src/components/popcorn/LikePopcorn.tsx
  src/components/popcorn/PopcornButtonBase.tsx
  src/pages/TestMainPage.tsx
  src/types/Popcorn.types.ts
Labels: BUILD, FEAT

#22 [POP-159] Feat: 검색바 구현
  package-lock.json
  package.json
  src/components/common/Header.tsx
  src/components/common/SearchBar.tsx
  src/routes/Layout.tsx
Labels: BUILD, STYLE, FEAT

#51 [POP-230] Refactor: 1차 인증 로직 보완 작업
  src/apis/userApi.ts
  src/components/LoginResgisterPage/LoginForm.tsx
  src/components/common/Header.tsx
  src/hooks/useAuthCheck.ts
  src/routes/Layout.tsx
Labels: REFACTOR, FEAT

#53 [Pop-232] Feat: 팝코리즘 API 연동
  src/apis/recommendApi.ts
  src/apis/recommendInstance.ts
  src/components/MainPage/HeroPopcorithm.tsx
  src/constants/contents.ts
  src/hooks/queries/contents/usePopcorithm.ts
  src/pages/MainPage.tsx
  src/types/Recommend.types.ts
Labels: REFACTOR, FEAT

#55 [POP-233] Feat : 비로그인 시, 메인 UI 블러처리
  public/images/poster/poster1.png
  public/images/poster/poster2.png
  public/images/poster/poster3.png
  public/images/poster/poster4.png
  public/images/poster/poster5.png
  public/images/poster/poster6.png
  public/images/poster/poster7.png
  src/components/MainPage/HeroPersona.tsx
  src/components/MainPage/HeroPopcorithm.tsx
  src/components/MainPage/HeroRanking.tsx
  src/components/common/LoginBlur.tsx
  src/components/common/Poster.tsx
  src/routes/Layout.tsx
Labels: STYLE, FEAT
